openapi: "3.0.3"
info:
  title: TAFE Weather API
  version: "1.0.0"
  description: "RESTful API to read, write, update and delete weather data."
tags:
  - name: weathers
    description: weather readings
  - name: users
    description: users information
  - name: logs
    description: deleted weather readings
paths:
  /api/v1/weathers/:
    get:
      tags:
        - weathers
      summary: List weather reading for all stations
      security:
        - bearerAuth: []
      operationId: listAllWeathers
      parameters:
        - name: limit
          in: query
          description: The maximum of results to return per page.
          schema:
            type: integer
            default: 10
            maximum: 50
        - name: page
          in: query
          description: The page number of results
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: A list of weather readings
          content:
            application/json:
              schema:
                type: object
                required:
                  - paging
                  - result
                properties:
                  paging:
                    type: object
                    properties:
                      totalCount:
                        type: integer
                        description: Total count of returned items
                      totalPages:
                        type: integer
                        description: Total pages of returned items
                      limit:
                        type: integer
                      currentPage:
                        type: integer
                  result:
                    type: array
                    items:
                      $ref: "#/components/schemas/Weather"
  /api/v1/weathers/{id}:
    get:
      tags:
        - weathers
      summary: Show a specific weather reading
      security:
        - bearerAuth: []
      operationId: showWeatherById
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the weather reading to retrive
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Weather"
components:
  schemas:
    Weather:
      type: object
      required:
        - _id
        - deviceName
        - precipitation
        - temperature
        - atmosphericPressure
        - maxWindSpeed
        - solarRadiation
        - vaporPressure
        - humidity
        - windDirection
        - geoLocation
        - createdAt
      properties:
        _id:
          type: string
          description: "Unique identifier of each weather reading document."
        deviceName:
          type: string
          minLength: 1
          maxLength: 50
          description: "Must be a string and is required, 1-50 characters"
        precipitation:
          type: number
          format: double
          description: "Must be a number, unit: mm/h"
        temperature:
          type: number
          format: double
          description: "Must be a number, unit: celsius degree"
        atmosphericPressure:
          type: number
          format: double
          description: "Must be a number, unit: kpa"
        maxWindSpeed:
          type: number
          format: double
          description: "Must be a number, unit: m/s"
        solarRadiation:
          type: number
          format: double
          description: "Must be a number, unit: w/m2"
        vaporPressure:
          type: number
          format: double
          description: "Must be a number, unit: kpa"
        humidity:
          type: number
          format: double
          description: "Must be a number, unit: %"
        windDirection:
          type: number
          format: double
          description: "Must be a number, unit: degree"
        createdAt:
          anyOf:
            - type: string
              description: "A string representation of the date."
            - type: object
              description: "An object representation of the date."
              required:
                - $date
              properties:
                $date:
                  type: object
                  required:
                    - $numberLong
                  properties:
                    $numberLong:
                      type: string
                      description: "The field must include a timestamp as a string."
        createdBy:
          type: string
          description: "User ID refer to who created the document"
        lastModifiedAt:
          type: string
          description: "The current timestamp when the document is updated"
        lastModifiedBy:
          type: string
          description: "User ID refer to who last modified the document"
        geoLocation:
          $ref: "#components/schemas#/GeoLocationOutput"
      additionalProperties: false
    GeoLocationOutput:
      type: object
      required:
        - type
        - coordinates
      properties:
        type:
          enum:
            - Point
          type: string
        coordinates:
          type: array
          minItems: 2
          maxItems: 2
          prefixItems:
            - $ref: "#/components/schemas/LongitudeInput"
            - $ref: "#/components/schemas/LatitudeInput"
    LongitudeInput:
      type: number
      format: double
      minimum: -180
      maximum: 180
      description: Longitude must be between -180 and 180 degrees
    LatitudeInput:
      type: number
      format: double
      minimum: -90
      maximum: 90
      description: Latitude must be between -90 and 90 degrees
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
