openapi: "3.1.0"
info:
  title: TAFE Weather API
  version: "1.0.0"
  description: "RESTful API to read, write, update and delete weather data."
tags:
  - name: weathers
    description: weather readings
  - name: users
    description: users information
  - name: logs
    description: deleted weather readings
paths:
  /api/v1/weathers/:
    get:
      tags:
        - weathers
      summary: List weather reading for all stations
      operationId: listAllWeathers
      parameters:
        - name: limit
          in: query
          description: The maximum of results to return per page.
          schema:
            type: integer
            default: 10
            maximum: 50
        - name: page
          in: query
          description: The page number of results
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: A list of weather readings
          content:
            application/json:
              schema:
                type: object
                required:
                  - paging
                  - result
                properties:
                  paging:
                    type: object
                    properties:
                      totalCount:
                        type: integer
                        description: Total count of returned items
                      totalPages:
                        type: integer
                        description: Total pages of returned items
                      limit:
                        type: integer
                      currentPage:
                        type: integer
                  result:
                    type: array
                    items:
                      $ref: "#components/schemas/Weather"
  /users:
    $ref: "./paths/users.yaml"
  /logs:
    $ref: "./paths/logs.yaml"
components:
  schemas:
    /weatherSchema:
      $ref: "./components/weatherSchema.yaml"
    /userSchema:
      $ref: "./components/userSchema.yaml"
    /logSchema:
      $ref: "./components/logSchema.yaml"
    /errorSchema:
      $ref: "./components/errorSchema.yaml"
